apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: cosmicbox
  labels:
    app: dashboard
spec:
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      namespace: cosmicbox
      labels:
        app: dashboard
    spec:
      containers:
        - image: danielemonteleone/cosmicbox-webapp:v0.2.0
          name: dashboard
          resources:
            requests:
              cpu: 20m
              memory: 50M
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: cosmicbox
spec:
  selector:
    app: dashboard
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard
  namespace: cosmicbox
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - eee.lsgalfer.it
      secretName: eee-lsgalfer-it-cert
  rules:
    - host: eee.lsgalfer.it
      http:
        paths:
          - path: /dashboard
            backend:
              serviceName: dashboard
              servicePort: 80
